### PR TITLE
Saved Searches layout (task #1928)

### PR DESCRIPTION
**Pull request by georgeconstantinou**
Updated saved searches layout to drop-down select list with view and delete functionality.

**Before:**
fireshot capture 32 - search - http___argusfx test qobocloud com_search_search_advanced_crmfx leads

**After:**
fireshot capture 31 - search - http___localhost_8010_search_search_advanced_crmfx leads

### CODE REVIEW

**Comment by flangofas** [comment]
:+1:

**Comment by leonidsl** [comment]
:+1:

**Comment by mamchenkov** [comment]
@georgeconstantinou beautiful!

One tiny thingy... the two "save search" fields are misaligned with the new dropdowns.  Maybe it's better to move them in the section below, where you are building the search.  Maybe, vertically, under the "Add filter" or something like that.  But really, not critical.  Now looks so much better! :)

**Comment by georgeconstantinou** [comment]
@mamchenkov please check updated layout:

fireshot capture 33 - search - http___localhost_8010_search_search_advanced_crmfx leads

**Comment by mamchenkov** [comment]
@georgeconstantinou stunningly beautiful! :)

**Pull request merged**
